workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      cocoapods: 1.12.0
      xcode: 14.2
      
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.avdevelopment.soundanalyser

      groups:
        - default
      vars:
        BUNDLE_ID: "com.avdevelopment.soundanalyser"
        XCODE_WORKSPACE: "SoundMeter.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "SoundMeter" # <-- Put the name of your Xcode scheme here
        APP_ID: 6446908832
    scripts:
      - name: X
        script: xcodebuild clean -workspace SoundMeter.xcworkspace -scheme SoundMeter -configuration Release
      - name: Delete derived data
        script: rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Make CERT KEY for pushes
       # Generate a private key
        script: openssl genrsa -out ios_distribution.key 2048 

      - name: Make csr for pushes
        script: openssl req -new -sha256 -key ios_distribution.key -out ios_distribution.csr -subj "/emailAddress=hnp@hnpproapp.com, CN=Nazarii Vertypolokh, C=RS"
    
      - name: Install CocoaPods dependencies
        script: |
          pod install
          
      - name: Update pod
        script: |
          pod update
          
      - name: Add linker flag
        script: |
          echo "OTHER_LDFLAGS=\$(OTHER_LDFLAGS) -ObjC" >> ./Pods/Target\ Support\ Files/Pods-SoundMeter/Pods-SoundMeter.release.xcconfig
          echo "OTHER_LDFLAGS=\$(OTHER_LDFLAGS) -ObjC" >> ./Pods/Target\ Support\ Files/Pods-SoundMeterNotificationServiceExtension/Pods-SoundMeterNotificationServiceExtension.release.xcconfig
      
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      #- name: Increment build number
      #  script: |
      #     cd $CM_BUILD_DIR
      #     LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID")
      #     agvtool new-version -all $(($LATEST_BUILD_NUMBER + 2))
      - name: clean
        script: |
          xcodebuild clean
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --verbose
            
    artifacts:
      - ios_distribution.key
      - ios_distribution.csr
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        expire_build_submitted_for_review: true

        beta_groups:
          - test 1
          - test 2

        submit_to_app_store: false
        #cancel_previous_submissions: true
        #release_type: MANUAL
